{application,map_red,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"map_red"},
              {modules,['Elixir.App','Elixir.ES','Elixir.Mapper',
                        'Elixir.NossoMap','Elixir.OpCustosa',
                        'Elixir.Particao']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
